version: '3.3'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WORDPRESS_USER}
      MYSQL_PASSWORD: ${WORDPRESS_PASS}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp_content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8000:80
  
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    volumes: db_data
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80


volumes:
  db_data: {}