wordpress-starter:
  image: wordpress
  links:
    - wordpress_db:mysql
  volumes:
    - ~/desktop/projects/WORDPRESS/wordpress/wp/wp-content/plugins/:/var/www/html/wp-content/plugins/
    - ~/desktop/projects/WORDPRESS/wordpress/wp/wp-content/themes/:/var/www/html/wp-content/themes/
  ports:
    - 80:80
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass  
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 81:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass